# Generated by Django 4.2.1 on 2023-06-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Pet Food'), ('T', 'Pet Toys'), ('S', 'Pet Service')], max_length=2),
        ),
    ]
